[tortoise]
# Tortoise ORM MySQL Database Configuration
db_url = "mysql://root:root@localhost:3306/chinatravel"
modules = { models = ["app.models"] }
use_spinlock = true
timezone = "UTC"

[aerich]
# Aerich Migration Configuration
location = "./migrations"
